(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ad-redefinition-action 'accept)
 '(auto-revert-check-vc-info t)
 '(backup-directory-alist '(("." . "~/.emacs.d/backup")))
 '(blink-cursor-mode nil)
 '(comp-async-jobs-number 9)
 '(company-auto-commit nil)
 '(company-box-enable-icon nil)
 '(company-dabbrev-downcase nil)
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 2)
 '(company-quickhelp-mode t)
 '(company-tooltip-align-annotations t)
 '(css-indent-offset 2)
 '(ctrlf-highlight-current-line nil)
 '(ctrlf-show-match-count-at-eol nil)
 '(dabbrev-check-other-buffers nil)
 '(dante-tap-type-time nil)
 '(ddskk-posframe-border-width 0)
 '(ddskk-posframe-mode t)
 '(delete-by-moving-to-trash t)
 '(delete-selection-mode t)
 '(desktop-path '("~/.emacs.d/" "~"))
 '(diff-hl-flydiff-mode t)
 '(diff-hl-side 'left)
 '(dired-no-confirm '(copy delete move))
 '(dired-recursive-deletes 'always)
 '(doom-themes-enable-italic nil)
 '(dracula-enlarge-headings nil)
 '(eglot-fsharp-server-install-dir "~/.emacs.d/misc/fsac")
 '(electric-pair-mode t)
 '(electric-pair-pairs '((34 . 34) (8216 . 8217) (8220 . 8221) (12300 . 12301)))
 '(enable-recursive-minibuffers nil)
 '(flycheck-check-syntax-automatically '(save mode-enabled))
 '(flycheck-disabled-checkers '(emacs-lisp emacs-lisp-checkdoc))
 '(flycheck-display-errors-delay 0.1)
 '(flycheck-emacs-lisp-load-path 'inherit)
 '(flycheck-ghc-args '("-Wall"))
 '(flycheck-html-tidy-executable "/usr/local/bin/tidy")
 '(frame-resize-pixelwise t)
 '(fsharp-indent-offset 2)
 '(global-auto-revert-mode t)
 '(global-company-mode t)
 '(global-flycheck-mode t)
 '(global-git-gutter-mode t)
 '(global-visual-line-mode nil)
 '(haskell-mode-stylish-haskell-path "ormolu")
 '(haskell-stylish-on-save t)
 '(helm-ag-base-command "rg --vimgrep --no-heading --smart-case")
 '(helm-ag-insert-at-point '\'symbol)
 '(helm-always-two-windows t)
 '(helm-autoresize-max-height 35)
 '(helm-buffer-max-length 40)
 '(helm-completion-style 'emacs)
 '(helm-inherit-input-method nil)
 '(helm-split-window-inside-p t)
 '(helm-swoop-speed-or-color t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(kill-whole-line t)
 '(line-spacing nil)
 '(lua-indent-level 2)
 '(magit-log-arguments '("-n256" "--graph" "--decorate" "--color"))
 '(magit-refresh-status-buffer nil)
 '(menu-bar-mode nil)
 '(modus-themes-org-blocks 'grayscale)
 '(modus-themes-subtle-line-numbers t)
 '(mouse-wheel-scroll-amount '(1 ((shift) . 1) ((control))))
 '(mozc-candidate-style 'posframe)
 '(org-adapt-indentation nil)
 '(org-archive-location "~/note/resource/archive.org::")
 '(org-blank-before-new-entry '((heading) (plain-list-item)))
 '(org-enable-table-editor nil)
 '(org-export-default-language "en")
 '(org-export-with-date nil)
 '(org-export-with-section-numbers nil)
 '(org-export-with-timestamps nil)
 '(org-export-with-toc nil)
 '(org-fontify-quote-and-verse-blocks t)
 '(org-fontify-whole-heading-line t)
 '(org-goto-auto-isearch nil)
 '(org-goto-interface 'outline)
 '(org-highlight-latex-and-related '(native))
 '(org-html-creator-string "")
 '(org-html-divs
   '((preamble "header" "preamble")
     (content "main" "content")
     (postamble "footer" "postamble")))
 '(org-html-doctype "html5")
 '(org-html-footnote-format "")
 '(org-html-head-include-default-style nil)
 '(org-html-head-include-scripts nil)
 '(org-html-html5-fancy t)
 '(org-html-htmlize-output-type nil)
 '(org-html-postamble nil)
 '(org-html-preamble nil)
 '(org-html-preamble-format nil)
 '(org-html-use-infojs nil)
 '(org-indirect-buffer-display 'other-window)
 '(org-log-done-with-time t)
 '(org-note-dir "~/documents/note/diary")
 '(org-outline-path-complete-in-steps nil)
 '(org-pomodoro-audio-player "paplay")
 '(org-pomodoro-finished-sound "~/.emacs.d/assets/bell.wav")
 '(org-pomodoro-format "%s")
 '(org-pomodoro-long-break-sound "~/.emacs.d/assets/bell.wav")
 '(org-pomodoro-short-break-sound "~/.emacs.d/assets/bell.wav")
 '(org-pomodoro-start-sound "~/.emacs.d/assets/start.wav")
 '(org-pomodoro-start-sound-p t)
 '(org-pomodoro-ticking-sound "~/.emacs.d/assets/tick.wav")
 '(org-pomodoro-ticking-sound-p nil)
 '(org-provide-todo-statistics 'all-headlines)
 '(org-src-fontify-natively t)
 '(org-src-tab-acts-natively nil)
 '(org-startup-folded 'showeverything)
 '(org-startup-truncated nil)
 '(org-startup-with-inline-images nil)
 '(org-todo-keywords '((sequence "TODO" "|" "DONE" "CANCELLED")))
 '(org-track-audio-player "paplay")
 '(org-track-format "%s")
 '(org-track-in-sound "~/.emacs.d/assets/start.wav")
 '(org-track-out-sound "~/.emacs.d/assets/bell.wav")
 '(org-use-fast-todo-selection nil)
 '(org-use-speed-commands t)
 '(outline-toc-update-delay 0.1)
 '(package-archives
   '(("melpa" . "https://melpa.org/packages/")
     ("gnu" . "https://elpa.gnu.org/packages/")))
 '(package-selected-packages
   '(modus-themes git-gutter projectile-ripgrep ripgrep flycheck-rust flymake-rust rust-mode 'pohe eglot-fsharp dart-mode git-gutter-fringe mozc-cand-posframe mozc-cursor-color mozc-posframe mozc-popup mozc-im mozc ahk-mode yasnippet org-make-toc toc-org ctrlf rg swiper-helm swiper helm-swoop org-pomodoro treemacs-magit org-sidebar dic-lookup-w3m treemacs dracula-theme lua-mode lsp-mode fsharp-mode yaml-mode helm-ag helm ddskk-posframe ddskk counsel-projectile projectile diff-hl markdown-mode magit multiple-cursors undo-fu dante haskell-mode spaceline spacemacs-theme company-box company flycheck-posframe flycheck paredit bind-key))
 '(pixel-scroll-mode nil)
 '(powerline-buffer-size-suffix nil)
 '(powerline-default-separator 'bar)
 '(powershell-indent 2)
 '(recentf-max-saved-items 10000)
 '(require-final-newline nil)
 '(ring-bell-function 'ignore)
 '(save-place-mode t)
 '(scroll-bar-mode nil)
 '(sh-basic-offset 2)
 '(size-indication-mode t)
 '(skk-auto-insert-paren t)
 '(skk-backup-jisyo "~/.skk/local-dictionary.bak")
 '(skk-cursor-hiragana-color "#5aa1f3")
 '(skk-egg-like-newline t)
 '(skk-henkan-show-candidates-keys '(49 50 51 52 53 54 55))
 '(skk-isearch-initial-mode-when-skk-mode-disabled 'latin)
 '(skk-isearch-mode-enable 'always)
 '(skk-isearch-mode-string-alist
   '((hiragana . "[あ] ")
     (katakana . "[ア] ")
     (jisx0208-latin . "[英] ")
     (latin . "[a] ")
     (abbrev . "[aあ] ")
     (nil . "[-] ")))
 '(skk-isearch-start-mode 'latin)
 '(skk-jisyo "~/.skk/local-dictionary")
 '(skk-jisyo-code 'utf-8)
 '(skk-jisyo-edit-user-accepts-editing t)
 '(skk-kakutei-key "
")
 '(skk-save-jisyo-instantly t)
 '(skk-server-inhibit-startup-server t)
 '(skk-show-candidates-nth-henkan-char 99)
 '(skk-show-inline nil)
 '(skk-special-midashi-char-list nil)
 '(skk-status-indicator 'minor-mode)
 '(skk-use-jisx0201-input-method t)
 '(skk-user-directory "~/.skk")
 '(spacemacs-theme-comment-bg t)
 '(spacemacs-theme-org-height nil)
 '(spacemacs-theme-org-highlight nil)
 '(swiper-stay-on-quit t)
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(treemacs-is-never-other-window t)
 '(treemacs-no-png-images t)
 '(treemacs-width 45)
 '(vc-follow-symlinks t)
 '(yas-global-mode t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ddskk-posframe ((t (:inherit company-tooltip))))
 '(flycheck-posframe-background-face ((t (:inherit company-tooltip))))
 '(org-drawer ((t (:inherit font-lock-keyword-face))))
 '(rainbow-delimiters-base-face ((t (:inherit nil :weight bold)))))

;; (custom-set-faces
;;  ;; custom-set-faces was added by Custom.
;;  ;; If you edit it by hand, you could mess it up, so be careful.
;;  ;; Your init file should contain only one such instance.
;;  ;; If there is more than one, they won't work right.
;;  '(ddskk-posframe ((t (:inherit company-tooltip))))
;;  '(flycheck-posframe-background-face ((t (:inherit company-tooltip))))
;;  '(fixed-pitch ((t nil)))
;;  '(vertical-border ((t (:foreground "#bbb")))))

;; (custom-set-faces
;;  ;; custom-set-faces was added by Custom.
;;  ;; If you edit it by hand, you could mess it up, so be careful.
;;  ;; Your init file should contain only one such instance.
;;  ;; If there is more than one, they won't work right.
;;  '(fringe ((t (:background "#efeae9" :foreground "#655370")))))
;; ;; (custom-set-faces
;; ;;  ;; custom-set-faces was added by Custom.
;; ;;  ;; If you edit it by hand, you could mess it up, so be careful.
;; ;;  ;; Your init file should contain only one such instance.
;; ;;  ;; If there is more than one, they won't work right.
;; ;;  )
